# Generated by Django 4.2.18 on 2025-02-01 18:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='баланс')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошелек',
            },
        ),
    ]
