# Generated by Django 4.2.18 on 2025-01-31 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000000000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='баланс')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошелек',
            },
        ),
    ]
